image: python:2.7-alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - pip install -r requirements.txt
    - pelican -s publishconf.py -o public
  artifacts:
    paths:
      - public/
