image: python:2.7-alpine

pages:
  script:
    - git clone https://github.com/getpelican/pelican-plugins.git
    - cd plugins && rm * && ln -s ../pelican-plugins/tipue_search && ln -s ../pelican-plugins/render_math && cd ..
    - pip install -r requirements.txt
    - pelican -s publishconf.py -o public
  artifacts:
    paths:
      - public/
